---
development:
  cloud_name: dkynumceo
  api_key: ENV.fetch("CLOUDINARY_API_KEY")
  api_secret: ENV.fetch("CLOUDINARY_API_SECRET")
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dkynumceo
  api_key: ENV.fetch("CLOUDINARY_API_KEY")
  api_secret: ENV.fetch("CLOUDINARY_API_SECRET")
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dkynumceo
  api_key: ENV.fetch("CLOUDINARY_API_KEY")
  api_secret: ENV.fetch("CLOUDINARY_API_SECRET")
  enhance_image_tag: true
  static_file_support: false
